export default [
  {
    id: "1123abc",
    name: "Niall Maher",
    title: "JavaScript Developer",
    username: "NiallJoeMaher",
    website: "www.codu.ie",
    skills: ["JavaScript", "CSS", "HTML", "NodeJS", "MongoDB", "AWS"],
  },
  {
    id: "234",
    name: "Adejo David",
    title: "JavaScript Developer",
    username: "dreplica",
    website: "github.com/dreplica",
    skills: [
      "JavaScript",
      "React & RNative",
      "CSS",
      "HTML",
      "NodeJS",
      "MongoDB",
      "AWS",
    ],
  },
  {
    id: "0181i762",
    name: "Praveen Kumar",
    title: "Full Stack Developer",
    username: "pkspyder007",
    website: "www.thejsguy.me",
    skills: [
      "JavaScript",
      "CSS",
      "HTML",
      "NodeJS",
      "MongoDB",
      "PHP",
      "Wordpress",
      "C/C++",
    ],
  },
  {
    id: "Sara0923ac",
    name: "Saranraj Santhanam",
    title: "Product Engineer",
    username: "saran-io",
    website: "foxolabs.com",
    skills: [
      "JavaScript",
      "CSS",
      "HTML",
      "NodeJS",
      "Firestore",
      "Golang",
      "Cloud",
      "C/C++",
    ],
  },
  {
    id: "amc1234",
    name: "Ann-Marie Cole",
    title: "JavaScript Developer",
    username: "annmariecl",
    website: "www.codu.ie",
    skills: ["JavaScript"],
  }
];
